import { Room, User, Booking } from '../types';
import { TIME_SLOTS } from './slots';
import { format, addDays } from 'date-fns';

export const INITIAL_USER: User = {
  id: 'usr_2026_9882',
  name: 'An Bình',
  studentId: '23IT020',
  email: 'anbinh.23it020@campus.edu.vn',
  department: 'Khoa Công nghệ Thông tin & AI',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
  role: 'student',
};

export const INITIAL_ROOMS: Room[] = [
  {
    id: 'room_a_101',
    name: 'Phòng Thảo Luận Sáng Tạo A101',
    code: 'A.101',
    building: 'A',
    floor: 1,
    capacity: 4,
    capacityCategory: 'small',
    amenities: ['whiteboard', 'air_conditioner'],
    imageUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop&q=80',
    description: 'Không gian yên tĩnh, trang bị bảng kính cường lực viết bút dạ, phù hợp cho nhóm 2-4 bạn làm bài tập lớn hoặc ôn thi.',
    rating: 4.8,
    reviewCount: 42,
    isPopular: true,
  },
  {
    id: 'room_a_204',
    name: 'Phòng Hội Thảo Nhỏ A204',
    code: 'A.204',
    building: 'A',
    floor: 2,
    capacity: 8,
    capacityCategory: 'medium',
    amenities: ['projector', 'whiteboard', 'air_conditioner'],
    imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&auto=format&fit=crop&q=80',
    description: 'Phòng tiêu chuẩn có máy chiếu sắc nét, cổng kết nối HDMI/Type-C, bàn chữ U tối ưu cho thuyết trình nhóm.',
    rating: 4.9,
    reviewCount: 78,
    isPopular: true,
  },
  {
    id: 'room_a_302',
    name: 'Phòng Nghiên Cứu Lab A302',
    code: 'A.302',
    building: 'A',
    floor: 3,
    capacity: 12,
    capacityCategory: 'large',
    amenities: ['projector', 'whiteboard', 'high_spec_pc', 'air_conditioner'],
    imageUrl: 'https://images.unsplash.com/photo-1517502884422-41eaead166d4?w=800&auto=format&fit=crop&q=80',
    description: 'Phòng máy cấu hình cao Core i9, 32GB RAM chuyên dụng cho đồ họa, mô phỏng dữ liệu và huấn luyện mô hình AI.',
    rating: 5.0,
    reviewCount: 115,
    isPopular: true,
  },
  {
    id: 'room_b_102',
    name: 'Phòng Nhóm Focus B102',
    code: 'B.102',
    building: 'B',
    floor: 1,
    capacity: 2,
    capacityCategory: 'small',
    amenities: ['air_conditioner'],
    imageUrl: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&auto=format&fit=crop&q=80',
    description: 'Phòng cách âm tuyệt đối dành cho cặp đôi học tập hoặc phỏng vấn trực tuyến quốc tế.',
    rating: 4.6,
    reviewCount: 35,
  },
  {
    id: 'room_b_205',
    name: 'Phòng Thuyết Trình B205',
    code: 'B.205',
    building: 'B',
    floor: 2,
    capacity: 6,
    capacityCategory: 'medium',
    amenities: ['projector', 'whiteboard', 'air_conditioner'],
    imageUrl: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=800&auto=format&fit=crop&q=80',
    description: 'Không gian mở tràn ngập ánh sáng tự nhiên với view sân trường, máy chiếu Full HD và bảng di động.',
    rating: 4.7,
    reviewCount: 53,
  },
  {
    id: 'room_b_401',
    name: 'Hội Trường Nhỏ B401',
    code: 'B.401',
    building: 'B',
    floor: 4,
    capacity: 20,
    capacityCategory: 'large',
    amenities: ['projector', 'whiteboard', 'air_conditioner'],
    imageUrl: 'https://images.unsplash.com/photo-1431540015161-0bf868a2d407?w=800&auto=format&fit=crop&q=80',
    description: 'Không gian rộng rãi, micro không dây, máy chiếu kép dành cho câu lạc bộ sinh viên sinh hoạt và workshop.',
    rating: 4.9,
    reviewCount: 92,
  },
  {
    id: 'room_c_105',
    name: 'Phòng Tự Học Nhóm C105',
    code: 'C.105',
    building: 'C',
    floor: 1,
    capacity: 4,
    capacityCategory: 'small',
    amenities: ['whiteboard', 'air_conditioner'],
    imageUrl: 'https://images.unsplash.com/photo-1571260899304-425eee4c7efc?w=800&auto=format&fit=crop&q=80',
    description: 'Bàn ghế công thái học, nhiều ổ cắm sạc nhanh type-C và không khí trong lành.',
    rating: 4.7,
    reviewCount: 29,
  },
  {
    id: 'room_c_303',
    name: 'Phòng Công Nghệ Số C303',
    code: 'C.303',
    building: 'C',
    floor: 3,
    capacity: 10,
    capacityCategory: 'large',
    amenities: ['projector', 'whiteboard', 'high_spec_pc', 'air_conditioner'],
    imageUrl: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800&auto=format&fit=crop&q=80',
    description: 'Trang bị 10 máy trạm đồng bộ, hệ thống mạng Gigabit LAN và màn hình phụ 27 inch 2K.',
    rating: 4.9,
    reviewCount: 84,
    isPopular: true,
  },
  {
    id: 'room_v_101',
    name: 'Phòng Đổi Mới Sáng Tạo V101',
    code: 'V.101',
    building: 'V',
    floor: 1,
    capacity: 8,
    capacityCategory: 'medium',
    amenities: ['projector', 'whiteboard', 'air_conditioner'],
    imageUrl: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=800&auto=format&fit=crop&q=80',
    description: 'Tòa nhà V-Tech mới khánh thành với thiết kế hiện đại, tường kính cách âm 2 lớp và bảng trượt thông minh.',
    rating: 5.0,
    reviewCount: 61,
    isPopular: true,
  },
  {
    id: 'room_v_202',
    name: 'Phòng Thí Nghiệm Đồ Họa V202',
    code: 'V.202',
    building: 'V',
    floor: 2,
    capacity: 16,
    capacityCategory: 'large',
    amenities: ['projector', 'whiteboard', 'high_spec_pc', 'air_conditioner'],
    imageUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&auto=format&fit=crop&q=80',
    description: 'Phòng máy chuẩn công nghiệp cho nhóm làm đồ án tốt nghiệp, game development và render kiến trúc.',
    rating: 4.8,
    reviewCount: 47,
  },
  {
    id: 'room_v_301',
    name: 'Phòng VIP Seminar V301',
    code: 'V.301',
    building: 'V',
    floor: 3,
    capacity: 14,
    capacityCategory: 'large',
    amenities: ['projector', 'whiteboard', 'air_conditioner'],
    imageUrl: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&auto=format&fit=crop&q=80',
    description: 'Không gian cao cấp view toàn cảnh thành phố, bàn hội nghị gỗ sồi và âm thanh vòm hội nghị.',
    rating: 4.9,
    reviewCount: 39,
  },
  {
    id: 'room_v_304',
    name: 'Phòng Nhóm Mini V304',
    code: 'V.304',
    building: 'V',
    floor: 3,
    capacity: 3,
    capacityCategory: 'small',
    amenities: ['whiteboard', 'air_conditioner'],
    imageUrl: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&auto=format&fit=crop&q=80',
    description: 'Góc học tập ấm cúng, riêng tư, trang bị đèn học bảo vệ mắt và ghế bành thư giãn.',
    rating: 4.7,
    reviewCount: 22,
  },
];

// Seed some initial bookings to demonstrate slot conflicts
export const getInitialBookings = (): Booking[] => {
  const today = format(new Date(), 'yyyy-MM-dd');
  const tomorrow = format(addDays(new Date(), 1), 'yyyy-MM-dd');

  return [
    {
      id: 'bk_seed_001',
      bookingCode: 'BK-A204-7192',
      roomId: 'room_a_204',
      roomName: 'Phòng Hội Thảo Nhỏ A204',
      roomCode: 'A.204',
      building: 'A',
      floor: 2,
      date: today,
      timeSlot: TIME_SLOTS[1], // 09:30 - 11:30
      userId: INITIAL_USER.id,
      userName: INITIAL_USER.name,
      studentId: INITIAL_USER.studentId,
      userEmail: INITIAL_USER.email,
      purpose: 'Thảo luận bài tập lớn môn Lập trình Di động',
      attendeesCount: 5,
      status: 'active',
      createdAt: new Date().toISOString(),
      qrPayload: JSON.stringify({
        code: 'BK-A204-7192',
        room: 'A.204',
        student: INITIAL_USER.studentId,
        date: today,
        slot: '09:30 - 11:30',
      }),
    },
    {
      id: 'bk_seed_002',
      bookingCode: 'BK-A302-8821',
      roomId: 'room_a_302',
      roomName: 'Phòng Nghiên Cứu Lab A302',
      roomCode: 'A.302',
      building: 'A',
      floor: 3,
      date: today,
      timeSlot: TIME_SLOTS[2], // 13:00 - 15:00
      userId: 'usr_other_4412',
      userName: 'Trần Minh Đức',
      studentId: '21127110',
      userEmail: 'duc.tm@campus.edu.vn',
      purpose: 'Huấn luyện mô hình Computer Vision',
      attendeesCount: 8,
      status: 'active',
      createdAt: new Date().toISOString(),
      qrPayload: JSON.stringify({
        code: 'BK-A302-8821',
        room: 'A.302',
        student: '21127110',
        date: today,
        slot: '13:00 - 15:00',
      }),
    },
    {
      id: 'bk_seed_003',
      bookingCode: 'BK-V101-3310',
      roomId: 'room_v_101',
      roomName: 'Phòng Đổi Mới Sáng Tạo V101',
      roomCode: 'V.101',
      building: 'V',
      floor: 1,
      date: tomorrow,
      timeSlot: TIME_SLOTS[0], // 07:30 - 09:30
      userId: 'usr_other_9901',
      userName: 'Lê Hoàng Yến',
      studentId: '22120033',
      userEmail: 'yen.lh@campus.edu.vn',
      purpose: 'Họp ban chủ nhiệm CLB Sinh viên',
      attendeesCount: 6,
      status: 'active',
      createdAt: new Date().toISOString(),
      qrPayload: JSON.stringify({
        code: 'BK-V101-3310',
        room: 'V.101',
        student: '22120033',
        date: tomorrow,
        slot: '07:30 - 09:30',
      }),
    },
  ];
};
